class TutorialVideosNotesModelStudyLabVLA {
  String classname,
      class_id,
      concept,
      Content_ID,
      date,
      duration,
      filename,
      format,
      path,
      professor,
      subjcet_id,
      subjectname,
      subject_code,
      thumbnail,
      TopicName,
      Topic_id;

  TutorialVideosNotesModelStudyLabVLA(
      this.classname,
      this.class_id,
      this.concept,
      this.Content_ID,
      this.date,
      this.duration,
      this.filename,
      this.format,
      this.path,
      this.professor,
      this.subjcet_id,
      this.subjectname,
      this.subject_code,
      this.thumbnail,
      this.TopicName,
      this.Topic_id);

  TutorialVideosNotesModelStudyLabVLA.fromJson(Map<String, dynamic> json)
      : classname = (json['classname'] == null) ? "" : json['classname'],
        class_id = (json['class_id'] == null) ? "" : json['class_id'],
        concept = (json['concept'] == null) ? "" : json['concept'],
        Content_ID = (json['Content_ID'] == null) ? "" : json['Content_ID'],
        date = (json['date'] == null) ? "" : json['date'],
        duration = (json['duration'] == null) ? "" : json['duration'],
        filename = (json['filename'] == null) ? "" : json['filename'],
        format = (json['format'] == null) ? "" : json['format'],
        path = (json['path'] == null) ? "" : json['path'],
        professor = (json['professor'] == null) ? "" : json['professor'],
        subjcet_id = (json['subjcet_id'] == null) ? "" : json['subjcet_id'],
        subjectname = (json['subjectname'] == null) ? "" : json['subjectname'],
        subject_code =
            (json['subject_code'] == null) ? "" : json['subject_code'],
        thumbnail = (json['thumbnail'] == null) ? "" : json['thumbnail'],
        TopicName = (json['TopicName'] == null) ? "" : json['TopicName'],
        Topic_id = (json['Topic_id'] == null) ? "" : json['Topic_id'];

  Map<String, dynamic> toJson() => {
        'classname': classname,
        'class_id': class_id,
        'concept': concept,
        'Content_ID': Content_ID,
        'date': date,
        'duration': duration,
        'filename': filename,
        'format': format,
        'path': path,
        'professor': professor,
        'subjcet_id': subjcet_id,
        'subjectname': subjectname,
        'subject_code': subject_code,
        'thumbnail': thumbnail,
        'TopicName': TopicName,
        'Topic_id': Topic_id,
      };
}
