// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7B_J-xN28hkBXTaV6b6I88uFqy4401u8',
    appId: '1:49340646797:android:b1b07dd95119ac5d1669c4',
    messagingSenderId: '49340646797',
    projectId: 'vidwath-app-notification',
    databaseURL: 'https://vidwath-app-notification.firebaseio.com',
    storageBucket: 'vidwath-app-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7B_J-xN28hkBXTaV6b6I88uFqy4401u8',
    appId: '1:49340646797:ios:0750195a4ae345ea1669c4',
    messagingSenderId: '49340646797',
    projectId: 'vidwath-app-notification',
    databaseURL: 'https://vidwath-app-notification.firebaseio.com',
    storageBucket: 'vidwath-app-notification.appspot.com',
    androidClientId: '49340646797-f7kb87ftd2v3jfrvj7ufknok3nmplns7.apps.googleusercontent.com',
    iosClientId: '406099696497-irb7edfevfkhi6t5s9kbuq1mt1og95rg.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );

}
